"use client";
import React from 'react';
import Link from 'next/link';
import { Award, ExternalLink, ArrowRight, Heart, Sparkles } from 'lucide-react';
import { useUser, SignUpButton } from '@clerk/react';
import { STARTER_TEMPLATES } from '../templates/starterTemplates';

export default function ShowcasePage({ onLoadTemplate, navigateTo }) {
  const { isSignedIn, isLoaded } = useUser();
  return (
    <div className="min-h-screen bg-[#090a0f] text-slate-100 py-16 px-6 max-w-7xl mx-auto select-none">
      {/* Header */}
      <div className="text-center max-w-2xl mx-auto mb-16">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-purple-500/30 bg-purple-500/10 text-purple-300 text-xs font-semibold mb-4">
          <Award className="w-3.5 h-3.5" />
          <span>Community Innovation</span>
        </div>
        <h1 className="text-4xl sm:text-5xl font-black text-white tracking-tight mb-4">
          Built with AetherCraft
        </h1>
        <p className="text-slate-400 text-sm">
          Discover cutting-edge websites, interactive dashboards, and fullstack apps generated by developers and founders using natural language prompts.
        </p>
      </div>

      {/* Featured Showcase Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
        {STARTER_TEMPLATES.map((tmpl) => (
          <div
            key={tmpl.id}
            className="rounded-3xl bg-[#0e121a] border border-white/10 overflow-hidden hover:border-indigo-500/40 transition duration-300 shadow-2xl flex flex-col justify-between group"
          >
            <div className="p-8">
              <div className="flex items-center justify-between mb-4">
                <span className="text-[11px] font-bold px-3 py-1 rounded-full bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 uppercase">
                  {tmpl.category}
                </span>
                <div className="flex items-center gap-1 text-xs text-rose-400">
                  <Heart className="w-3.5 h-3.5 fill-rose-400" />
                  <span className="font-semibold">{tmpl.stars + 120}</span>
                </div>
              </div>

              <h3 className="text-2xl font-bold text-white mb-2 group-hover:text-indigo-300 transition">
                {tmpl.name}
              </h3>
              <p className="text-xs text-slate-400 leading-relaxed mb-6 font-light">
                {tmpl.description}
              </p>

              <div className="flex flex-wrap gap-2 mb-4">
                {tmpl.tags?.map((t, idx) => (
                  <span key={idx} className="text-xs px-2.5 py-1 rounded-lg bg-white/5 text-slate-300">
                    {t}
                  </span>
                ))}
              </div>
            </div>

            <div className="p-6 bg-black/40 border-t border-white/5 flex items-center justify-between">
              <div className="text-xs text-slate-400">
                Created by <span className="text-white font-medium">{tmpl.author}</span>
              </div>
              {(!isLoaded || !isSignedIn) ? (
                <Link
                  role="button"
                  href="/signup"
                  onClick={(e) => {
                    if (navigateTo) {
                      e.preventDefault();
                      navigateTo('signup');
                    }
                  }}
                  className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:opacity-90 text-white text-xs font-bold transition shadow-lg shadow-indigo-600/25 cursor-pointer"
                >
                  <span>Clone & Edit Project</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              ) : (
                <button
                  onClick={() => onLoadTemplate(tmpl)}
                  className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:opacity-90 text-white text-xs font-bold transition shadow-lg shadow-indigo-600/25 cursor-pointer"
                >
                  <span>Clone & Edit Project</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Submission Banner */}
      <div className="rounded-3xl p-10 bg-gradient-to-r from-purple-950/30 to-indigo-950/30 border border-white/10 text-center">
        <h3 className="text-2xl font-bold text-white mb-2">Want your app featured here?</h3>
        <p className="text-xs text-slate-400 max-w-md mx-auto mb-6">
          Build something amazing in the Studio, click Export, and submit your project to join over 500 featured community apps.
        </p>
        {(!isLoaded || !isSignedIn) ? (
          <Link
            role="button"
            href="/signup"
            onClick={(e) => {
              if (navigateTo) {
                e.preventDefault();
                navigateTo('signup');
              }
            }}
            className="px-6 py-3 rounded-xl bg-white/10 hover:bg-white/15 text-white text-xs font-semibold transition cursor-pointer inline-block"
          >
            Start Building Your App
          </Link>
        ) : (
          <button
            onClick={() => navigateTo('studio')}
            className="px-6 py-3 rounded-xl bg-white/10 hover:bg-white/15 text-white text-xs font-semibold transition cursor-pointer"
          >
            Start Building Your App
          </button>
        )}
      </div>
    </div>
  );
}

